version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user_name
      MONGO_INITDB_ROOT_PASSWORD: user_password
    ports:
      - "27017:27017"
    volumes:
      - "./db:/data/db"

  app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - mongo
    environment:
      - MONGODB_USERNAME=user_name
      - MONGODB_PASSWORD=user_password
      - MONGODB_HOSTNAME=mongo
