version: '3.8'

services: 
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user_name
      MONGO_INITDB_ROOT_PASSWORD: user_password
    ports:
      - "27017:27017"  
    volumes:  
      - "./db:/data/db"

  app: 
    build: . 
    restart: always  
    ports: 
      - "8501:8501" 
    depends_on:  
      - mongo  
