name: CI/CD with Docker Compose

on:
  push:
    branches:
      - main  # Déclenche le workflow sur chaque push sur la branche "main"

jobs:
  build:
    runs-on: self-hosted  # Utilise le runner self-hosted local

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout code
        uses: actions/checkout@v2
        with :
          clean : false  # Ne pas supprimer les fichiers existants

      # Étape 2 : Configurer Docker Buildx (optionnel si nécessaire)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Étape 3 : Construire et démarrer les services Docker
      - name: Start MongoDB and the app with Docker Compose
        run: |
          docker compose up --build
  

      
